apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcraftsman-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ap-hyderabad-1.ocir.io/$TENANCY_NAME/$NAMESPACE/REPOSITORY_URI:latest
          ports:
            - containerPort: 8001
          env:
            - name: MYSQL_HOST
              value: $MYSQL_HOST
            - name: MYSQL_DB
              value: $MYSQL_DB
            - name: MYSQL_USER
              value: $MYSQL_USER
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD
            - name: GH_CLIENT_ID
              value : $GH_CLIENT_ID
            - name: GH_SECRET_ID
              value : $GH_SECRET_ID
            - name: OPENAI_API_KEY
              value : $OPENAI_API_KEY
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: devcraftsman-api-service
spec:
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: LoadBalancer
